distance: 30
port: 108
id_label_path: results/id_label_108_0.csv
input_video_path: video/transport/32.31.250.108/20240501_20240501113543_20240501135236_113542.mp4
json_path: results/108_0.json
list_pts_blue:  [[935, 345], [945, 300], [650, 255], [510, 265]]
list_pts_green:  [[750, 440], [350, 450],[290,280], [370, 270]]
list_pts_yellow: [[925, 350], [800, 430], [400, 270], [480, 270]]
offset: 0.8
floor: 30S
time_series: results/30S/time_series_108_0.csv
