distance: 30
port: 103
id_label_path: results/id_label_103_1.csv
input_video_path: video/transport/32.31.250.103/20240501_20240501140806_20240501152004_140807.mp4
json_path: results/103_1.json
list_pts_blue:  [[25, 200], [50, 250], [365, 150], [260, 150]]
list_pts_yellow: [[185, 366], [60, 260], [370, 150], [485, 150]]
list_pts_green:  [[500, 520], [200, 370], [495, 150], [585, 150]]
offset: 0.7
floor: 30S
time_series: results/30S/time_series_103_1.csv
