distance: 30
port: 105
id_label_path: results/id_label_105_0.csv
input_video_path: video/transport/32.31.250.105/20240501_20240501115227_20240501130415_115227.mp4
json_path: results/105_0.json
list_pts_blue:  [[25, 185], [40, 230], [340, 145], [225, 145]]
list_pts_green:  [[430, 480], [175, 340], [430,150], [490, 150]]
list_pts_yellow: [[140, 330], [50, 240], [355, 150], [420, 150]]
offset: 0.7
floor: 30S
time_series: results/30S/time_series_105_0.csv
